
name: Deploy PowerPoint Site

on:
  workflow_dispatch:
  # Uncomment the below trigger for scheduled runs - just gonna run it like once more in case of problems
  # schedule:
  # #   # Every Saturday at 12:00PM UTC (10:00PM AEST)
  #   - cron: '0 12 * * 6'
  workflow_run:
    workflows: ["Create PowerPoint and push to main"]
    types:
      - completed # Trigger when the specified workflow completes

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Generate HTML
        run: python Scripts/generate_html.py

      - name: Prepare deployment files
        run: |
          mkdir deploy
          cp -r "Complete slides" deploy/
          cp index.html deploy/
          cp styles.css deploy/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
