name: IP address info

permissions:
  contents: write  # <-- This is what gives the GitHub Actions bot push rights

on:
  workflow_dispatch:
  # Uncomment the below trigger for scheduled runs
  # schedule:
  #   # Every Saturday at 11:45AM UTC (9:45PM AEST)
  #   - cron: '45 11 * * 6'
jobs:
  IP-Address:
    runs-on: windows-latest
    environment: prod
    name: IP address info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Print ipconfig info
        run: |
          ipconfig
          where netsh
      - name: Print IP interfaces
        run: |
          powershell -Command "Get-NetIPInterface"
          where netsh
      - name: Change IP interfaces
        run: |
          powershell -Command "Set-NetIPAddress -InterfaceIndex 14 -IPAddress 192.168.0.42 -PrefixLength 16 -PreferredLifetime (New-TimeSpan -Days 1)"
          powershell -Command "Set-NetIPAddress -InterfaceIndex 10 -IPAddress 172.20.16.7 -PrefixLength 20 -PreferredLifetime (New-TimeSpan -Days 1)"
          ipconfig
