name: Create PowerPoint and push to main

permissions:
  contents: write

on:
  workflow_dispatch:
  # Uncomment the below trigger for scheduled runs
  schedule:
    # Every Saturday at 11:45AM UTC (9:45PM AEST)
    - cron: '45 11 * * 6'
jobs:
  Generate-PowerPoint-into-branch:
    runs-on: ubuntu-latest
    environment: prod
    name: Create PowerPoint file into main branch
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
      - name: Create PowerPoint
        run: |
          python ./Scripts/new_powerpoint_maker_auto.py
        env:
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          CCLI_NUM: ${{ vars.CCLI_NUM }}
          PYTHONUTF8: 1
          CCLI_URL: ${{ secrets.CCLI_URL }}
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
          ROSTER_SHEET_LINK: ${{vars.ROSTER_SHEET_LINK}}
      - name: Push change to main
        run: |
          python ./Scripts/pptx_push_to_main.py
